Remove xlstproc and fix docs bugs

diff --git a/docs/html/Makefile.am b/docs/html/Makefile.am
--- a/docs/html/Makefile.am
+++ b/docs/html/Makefile.am
@@ -7,69 +7,32 @@ TARGET_DIR = @XMLSEC_DOCDIR@
 
 # Markdown source files for generated HTML pages (all *.md in docs/md/)
 MD_SRCDIR     = $(top_srcdir)/docs/md
-MD_SRC_FILES  = $(wildcard $(MD_SRCDIR)/*.md)
+MD_BUILDDIR   = $(top_builddir)/docs/md
+MD_SRC_FILES  = \
+	$(wildcard $(MD_SRCDIR)/*.md) \
+	$(wildcard $(MD_BUILDDIR)/*.md) \
+	$(NULL)
 
 # files that are copied from sources
 EXTRA_DIST := \
 	$(srcdir)/images 					\
 	$(srcdir)/css 						\
-	$(srcdir)/xmlsec.xsl				\
 	$(srcdir)/pandoc-template.html5		\
 	$(srcdir)/favicon.ico				\
     $(NULL)
 
-.PHONY: all docs docs-copy docs-md
+.PHONY: all docs docs-copy docs-build-html
 
 all:
 	@echo "======= Run 'make docs' in the xmlsec/docs folder to rebuild docs"
 
+docs: docs-copy docs-build-html
 
-# if we build html docs then we need to have xsltproc
+
 if BUILD_HTML_DOCS
-
-docs: docs-copy docs-md
-	@(echo "-- Formatting html documents"; \
-	for i in `find $(builddir) -name "*.html" -print`; \
-	do \
-	    top_folder=`echo $$i | $(SED) 's#/[^/]*$$#/#' | $(SED) 's#\./##' | \
-			$(SED) 's#[^/]*/#../#g'`; \
-	    echo "--- Processing $$i (topfolder='$$top_folder')"; \
-	    $(XSLTPROC) --html --stringparam topfolder "$$top_folder" \
-		     --output $$i.tmp $(srcdir)/xmlsec.xsl $$i; \
-	    if [ $$? != 0 ]; \
-	    then \
-			echo "ERROR: processing file $$i"; \
-			exit 1; \
-	    fi; \
-	    $(MV) $$i.tmp $$i; \
-	done)
-	@(echo "-- Cleaning html documents"; \
-	for i in `find $(builddir) -name "*.html" -print`; \
-	do \
-	    echo "--- Cleaning $$i" ; \
-	    $(SED) 's/\xC2\xA0/ /g' $$i > $$i.tmp ; \
-	    $(MV) $$i.tmp $$i ; \
-	done)
-	@$(MAKE) $(AM_MAKEFLAGS)
-
-else
-
-docs: docs-copy docs-md
-	@( \
-		echo "=== ERROR: To build docs, make sure all necessary tools are installed" ; \
-		echo "SED:      $(SED)" ; \
-		echo "SORT:     $(SORT)" ; \
-		echo "XSLTPROC: $(XSLTPROC)" ; \
-		exit 1; \
-	)
-
-endif
-
 # Convert all *.md files from docs/md/ to HTML using pandoc.
-# The pandoc template adds the <head> structure; xsltproc (above) then wraps
-# each output with the navigation panel just like all other HTML pages.
-if BUILD_MD_DOCS
-docs-md: $(MD_SRC_FILES)
+# The pandoc template adds the navigation panel and <head> structure.
+docs-build-html: $(MD_SRC_FILES)
 	@echo "-- Generating HTML from Markdown files in $(MD_SRCDIR) ..."
 	@for f in $(MD_SRC_FILES); do \
 		out=$(builddir)/`basename $$f .md`.html ; \
@@ -80,17 +43,27 @@ docs-md: $(MD_SRC_FILES)
 			--from=markdown --to=html5 \
 			--output=$$out \
 			$$f ; \
+		$(SED) -E -i 's|href="(\.\./)*api/index\.md(#[^"]*)?"|href="https://github.com/lsh123/xmlsec/wiki/API-Index\2"|g' $$out ; \
+		$(SED) -E -i 's|href="(\.\./)*tutorial/index\.md(#[^"]*)?"|href="https://github.com/lsh123/xmlsec/wiki/Tutorial-Index\2"|g' $$out ; \
+		$(SED) -E -i 's|href="(\.\./)*examples/index\.md(#[^"]*)?"|href="https://github.com/lsh123/xmlsec/wiki/Examples-Index\2"|g' $$out ; \
+		$(SED) -E -i 's|href="([^"#:]*)\.md(#[^"]*)?"|href="\1.html\2"|g' $$out ; \
 	done
 else
-docs-md:
-	@echo "-- Note: Skipping Markdown-to-HTML generation (pandoc not available)"
+docs-build-html:
+	@( \
+		echo "=== ERROR: To build docs, make sure all necessary tools are installed" ; \
+		echo "SED:      $(SED)" ; \
+		echo "SORT:     $(SORT)" ; \
+		echo "PANDOC:   $(PANDOC)" ; \
+		exit 1; \
+	)
+
 endif
 
 docs-copy:
 	@( \
 		echo "-- Copying source html to build folder ..." ; \
 		if [ z"$(srcdir)" != z"$(builddir)" ] ; then  \
-			$(CP)  $(srcdir)/*.html $(builddir)/ ; \
 			$(CP)  $(srcdir)/*.ico $(builddir)/ ; \
 			mkdir -p  $(builddir)/images $(builddir)/css ; \
 			$(CP) -r $(srcdir)/images/* $(builddir)/images/ ; \
@@ -102,24 +75,12 @@ docs-copy:
 clean-local:
 	@( \
 		$(RM) -f *.stamp ; \
+		$(RM) -rf $(builddir)/*.html ; \
 		if [ z"$(srcdir)" != z"$(builddir)" ] ; then \
 			(chmod -Rf u+w $(builddir)/*.html 2>/dev/null || true) ; \
-			$(RM) -rf $(builddir)/*.html ; \
+			$(RM) -rf $(builddir)/*.ico ; \
 			$(RM) -rf $(builddir)/images ; \
 			$(RM) -rf $(builddir)/css ; \
 		fi ; \
 	 )
-
-dist-hook:
-	@( \
-		if test -f $(builddir)/index.html ; then  \
-			echo "-- Copying to dist builddir html docs ..." ; \
-			$(CP) $(builddir)/*.html $(distdir)/ ; \
-		else \
-			echo "-- Copying to dist source html docs ..." ; \
-			$(CP) $(srcdir)/*.html $(distdir)/ ; \
-		fi ; \
-	)
-
-distclean-local: clean-local
 
