Cleanup build Makefiles and remove config.h.in (#1102)

diff --git a/docs/api/Makefile.am b/docs/api/Makefile.am
--- a/docs/api/Makefile.am
+++ b/docs/api/Makefile.am
@@ -76,21 +76,22 @@ all: docs-copy
 
 # if build API docs, then we also have xsltproc
 if BUILD_API_DOCS
-docs: docs-copy html-cleanup copy-images
+docs: html-cleanup
 
 else
 
 docs: docs-copy
-	@echo "To build API docs, pass '--enable-docs-build' to './configure' script and make sure all necessary tools are installed"
+	@echo "ERROR: To build API docs, make sure all necessary tools are installed"
 
 endif
 
 docs-copy:
 	@( \
-		echo "-- Copying api-docs..."; \
+		echo "-- Copying api docs..."; \
 		if [ z"$(srcdir)" != z"$(builddir)" ]; \
 		then \
-		    $(CP) -r $(SOURCE_FILES_TO_COPY) $(builddir)/ ; \
+			(chmod -Rf u+w $(EXTRA_DIST)  2>/dev/null || true) ; \
+			$(CP) -r $(SOURCE_FILES_TO_COPY) $(builddir)/ ; \
 		fi \
 	)
 
@@ -99,8 +100,7 @@ html-cleanup: html
 	   $(PERL) $(REMOVE_GTKDOCLINK) `find . -name "*.html" -print` \
 	)
 
-# need to cleanup "bad" chars
-html: sgml $(MAIN_SGML_FILE) $(SGML_CHAPTERS_DIR) xmlsec-index
+html: docs-copy sgml $(MAIN_SGML_FILE) $(SGML_CHAPTERS_DIR) xmlsec-index
 	@$(GTKDOC_MKHTML) xmlsec $(MAIN_SGML_FILE)
 
 $(SGML_CHAPTERS_DIR): $(SGML_CHAPTERS_SRC_DIR) $(SGML_CHAPTERS_DIR)/.sentinel
@@ -261,12 +261,6 @@ example_sources: $(EXAMPLES_DIR)/.sentinel
 		    $(EXAMPLES_DIR)/$$file_name.sgml; \
 	done);
 
-copy-images:
-	@( if [ z"$(builddir)" != z"$(srcdir)" ] ; then \
-		echo "Copying images ..." ; \
-		mkdir -p $(builddir)/images ; \
-		cp $(srcdir)/images/*.png $(builddir)/images/ ; \
-	fi ; )
 
 # A single pattern rule will create all appropriate folders as required
 # otherwise make (annoyingly) deletes it
@@ -292,8 +286,8 @@ clean-local:
 	@( \
 		if [ z"$(builddir)" != z"$(srcdir)" ] ; \
 		then \
-			(chmod -R u+w $(builddir)/xmlsec.devhelp2 $(EXTRA_DIST)  || true) ; \
-    		rm -rf $(builddir)/xmlsec.devhelp2 $(EXTRA_DIST) ; \
+			(chmod -Rf u+w $(builddir)/xmlsec.devhelp2 $(EXTRA_DIST) 2>/dev/null || true) ; \
+			rm -rf $(builddir)/xmlsec.devhelp2 $(EXTRA_DIST) ; \
 	 	fi ; \
 	)
 
