Simplify docs build and avoid un-necessary copies (#1105)

diff --git a/docs/Makefile.am b/docs/Makefile.am
--- a/docs/Makefile.am
+++ b/docs/Makefile.am
@@ -4,66 +4,28 @@ SUBDIRS=api
 
 TARGET_DIR=@XMLSEC_DOCDIR@
 
-# we copy over all folders to builddir to make it easier to test docs
-EXTRA_DIST=	                \
-    $(builddir)/images      \
-    $(builddir)/css         \
-    $(builddir)/*.html      \
-    $(builddir)/*.ico       \
-    $(builddir)/*.xsl       \
-    $(NULL)
 
-SOURCE_FILES_TO_COPY=       \
-    $(srcdir)/images        \
-    $(srcdir)/css           \
-    $(srcdir)/*.html        \
-    $(srcdir)/*.ico         \
-    $(srcdir)/*.xsl         \
+# files that are copied from sources
+EXTRA_DIST := \
+	$(srcdir)/images 					\
+	$(srcdir)/css 						\
+	$(srcdir)/xmlsec.xsl				\
+	$(srcdir)/favicon.ico				\
     $(NULL)
 
 XMLSEC1_MAN=$(builddir)/../man/xmlsec1.1
 XMLSEC_HTML=$(builddir)/xmlsec-man.html
 
-all: docs-copy
+.PHONY: all docs docs-api docs-manpages docs-copy
+
+all:
 	@echo "======= Run 'make docs' in the xmlsec/docs folder to rebuild docs"
-
-docs: docs-api docs-copy man-docs docs-format
-
-docs-api:
-	make -C api docs
-
-docs-copy:
-	@( \
-		echo "-- Copying docs..."; \
-		if [ z"$(srcdir)" != z"$(builddir)" ]; \
-		then \
-		    (chmod -Rf u+w $(EXTRA_DIST)  2>/dev/null || true) ; \
-		    $(CP) -r $(SOURCE_FILES_TO_COPY) $(builddir)/  ; \
-		fi \
-	)
-
-if BUILD_MAN_DOCS
-man-docs: $(XMLSEC_HTML)
-
-$(XMLSEC_HTML): docs-copy $(XMLSEC1_MAN)
-	@echo "-- Building docs for man page ..."
-	@($(MAN2HTML) $(XMLSEC1_MAN) | \
-		  $(GREP) -v '^Content-type: text/html' | \
-		  tr "[:cntrl:]" " " > \
-		  $(XMLSEC_HTML) \
-	)
-else
-
-# do nothing, we aready copied this file
-man-docs: docs-copy
-
-endif
 
 
 # if we build api docs then we also have xsltproc
 if BUILD_API_DOCS
 
-docs-format: man-docs
+docs: docs-manpages docs-api docs-copy
 	@(echo "-- Formatting html documents"; \
 	for i in `find $(builddir) -name "*.html" -print`; \
 	do \
@@ -89,33 +51,82 @@ docs-format: man-docs
 
 else
 
-# do nothing, we aready copied this file
-docs-format: man-docs
+docs: docs-manpages docs-api
+	@(echo "=== ERROR: To build docs, make sure all necessary tools are installed" ; exit 1; )
 
 endif
 
+if BUILD_MAN_DOCS
+docs-manpages: docs-copy $(XMLSEC1_MAN)
+	@echo "-- Building docs for man page ..."
+	@($(MAN2HTML) $(XMLSEC1_MAN) | \
+		  $(GREP) -v '^Content-type: text/html' | \
+		  tr "[:cntrl:]" " " > \
+		  $(XMLSEC_HTML) \
+	)
+else
+
+docs-manpages: docs-copy
+	@echo "-- Skipping building docs for man page ..."
+
+endif
+
+docs-copy:
+	@( \
+		echo "-- Copying source html to build folder ..." ; \
+		if [ z"$(srcdir)" != z"$(builddir)" ] ; then  \
+			$(CP)  $(srcdir)/*.html $(builddir)/ ; \
+		fi ; \
+	)
+
+docs-api:
+	make -C api docs
 
 clean-local:
 	@( \
 		$(RM) -f *.stamp ; \
-		if [ z"$(srcdir)" != z"$(builddir)" ] ; \
-		then \
-			(chmod -Rf u+w $(EXTRA_DIST)  2>/dev/null || true) ; \
-			$(RM) -rf $(EXTRA_DIST) ; \
+		if [ z"$(srcdir)" != z"$(builddir)" ] ; then \
+			(chmod -Rf u+w $(builddir)/*.html 2>/dev/null || true) ; \
+			$(RM) -rf $(builddir)/*.html ; \
 		fi ; \
 	 )
+
+dist-hook:
+	@( \
+		if test -f $(builddir)/index.html ; then  \
+			echo "-- Copying to dist builddir html docs ..." ; \
+			$(CP) $(builddir)/*.html $(distdir)/ ; \
+		else \
+			echo "-- Copying to dist source html docs ..." ; \
+			$(CP) $(srcdir)/*.html $(distdir)/ ; \
+		fi ; \
+	)
 
 distclean-local: clean-local
 
 install-data-local:
-	@echo "Installing docs ..."
-	@$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)
-	@$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)/images
-	@$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)/css
-	@INSTALL@ -m 0644 $(builddir)/*.html $(DESTDIR)$(TARGET_DIR)
-	@INSTALL@ -m 0644 $(builddir)/*.ico  $(DESTDIR)$(TARGET_DIR)
-	@INSTALL@ -m 0644 $(builddir)/images/*.gif $(builddir)/images/*.png $(DESTDIR)$(TARGET_DIR)/images
-	@INSTALL@ -m 0644 $(builddir)/css/*.css $(DESTDIR)$(TARGET_DIR)/css
+	@( \
+		$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR) ; \
+		if test -f $(builddir)/index.html ; then  \
+			echo "-- Installing builddir html docs ..." ; \
+			@INSTALL@ -m 0644 $(builddir)/*.html $(DESTDIR)$(TARGET_DIR) ; \
+		else \
+			echo "-- Installing srcdir html docs ..." ; \
+			@INSTALL@ -m 0644 $(srcdir)/*.html $(DESTDIR)$(TARGET_DIR) ; \
+		fi ; \
+	)
+	@( \
+		echo "-- Installing images ..." ; \
+		$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)/images ; \
+		@INSTALL@ -m 0644 $(srcdir)/*.ico  $(DESTDIR)$(TARGET_DIR) ; \
+		@INSTALL@ -m 0644 $(srcdir)/images/*.gif $(DESTDIR)$(TARGET_DIR)/images/ ; \
+		@INSTALL@ -m 0644 $(srcdir)/images/*.png $(DESTDIR)$(TARGET_DIR)/images/ ; \
+	)
+	@( \
+		echo "-- Installing css ..." ; \
+		$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)/css ; \
+		@INSTALL@ -m 0644 $(srcdir)/css/*.css $(DESTDIR)$(TARGET_DIR)/css/ ; \
+	)
 
 uninstall-local:
 	@$(RM) -rf $(DESTDIR)$(TARGET_DIR)
